// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VeiculosAPI2.Entities;

namespace VeiculosAPI2.Migrations
{
    [DbContext(typeof(VeiculosContext))]
    [Migration("20201127152058_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("VeiculosAPI2.Entities.Caminhao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("CREATED_AT")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnName("UPDATED_AT")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("cor")
                        .HasColumnName("COR")
                        .HasColumnType("text");

                    b.Property<long>("id")
                        .HasColumnType("bigint");

                    b.Property<string>("marca")
                        .HasColumnName("MARCA")
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .HasColumnName("MODELO")
                        .HasColumnType("text");

                    b.Property<int>("numeroEixos")
                        .HasColumnName("NUMERO_EIXOS")
                        .HasColumnType("integer");

                    b.Property<string>("placa")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("id");

                    b.ToTable("T_CAMINHAO");
                });

            modelBuilder.Entity("VeiculosAPI2.Entities.Carro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("CREATED_AT")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnName("UPDATED_AT")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("cor")
                        .HasColumnName("COR")
                        .HasColumnType("text");

                    b.Property<long>("id")
                        .HasColumnType("bigint");

                    b.Property<string>("marca")
                        .HasColumnName("MARCA")
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .HasColumnName("MODELO")
                        .HasColumnType("text");

                    b.Property<string>("placa")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("id");

                    b.ToTable("T_CARRO");
                });

            modelBuilder.Entity("VeiculosAPI2.Entities.Moto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<int>("CapotesDoGustavao")
                        .HasColumnName("CAPOTES_DO_GUSTAVAO")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("CREATED_AT")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnName("UPDATED_AT")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("cor")
                        .HasColumnName("COR")
                        .HasColumnType("text");

                    b.Property<long>("id")
                        .HasColumnType("bigint");

                    b.Property<string>("marca")
                        .HasColumnName("MARCA")
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .HasColumnName("MODELO")
                        .HasColumnType("text");

                    b.Property<int>("numeroQuedas")
                        .HasColumnName("NUMERO_QUEDAS")
                        .HasColumnType("integer");

                    b.Property<string>("placa")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("id");

                    b.ToTable("Moto");
                });
#pragma warning restore 612, 618
        }
    }
}
